#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def normalize_slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")
    return slug or "helper_tool"


def infer_helper_category(helper_name: str, purpose: str, category: str | None) -> str:
    if category:
        return category
    lowered = f"{helper_name} {purpose}".lower()
    if "timeout" in lowered or "stall" in lowered or "hang" in lowered:
        return "runtime_timeout"
    if "missing" in lowered or "no tool" in lowered or "unsupported" in lowered:
        return "tool_missing"
    if "blocked" in lowered or "no response" in lowered:
        return "execution_blocked"
    if "drift" in lowered or "bundle" in lowered or "patch" in lowered:
        return "runtime_drift"
    return "generic"


def render_helper(helper_name: str, purpose: str, category: str) -> str:
    return f"""#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


HELPER_NAME = {helper_name!r}
PURPOSE = {purpose!r}
CATEGORY = {category!r}


def collect_checks(repo_root: Path, observation: str) -> tuple[list[dict[str, object]], list[str]]:
    checks: list[dict[str, object]] = []
    suggestions: list[str] = []
    expected = [
        "scripts/openclaw/agent_society_runtime_record_gap.py",
        "scripts/openclaw/agent_society_helper_toolsmith.py",
        "scripts/openclaw/patch_line_direct_visibility_watchdog_current.py",
    ]
    for rel in expected:
        path = repo_root.joinpath(*rel.split("/"))
        checks.append({{
            "kind": "path_exists",
            "path": rel,
            "ok": path.exists(),
        }})
    lowered = observation.lower()
    if CATEGORY == "runtime_timeout":
        suggestions.append("inspect direct-task timeout and first-response watchdog thresholds before retrying")
        if "line" in lowered or "response" in lowered:
            suggestions.append("verify LINE direct visibility watchdog and no-response fallback are both patched in the active runtime")
    elif CATEGORY == "execution_blocked":
        suggestions.append("classify whether the block is channel delivery, runtime execution, or missing target discovery")
        if "no response" in lowered:
            suggestions.append("check whether no-response fallback is present before escalating to model/runtime diagnosis")
    elif CATEGORY == "tool_missing":
        suggestions.append("identify the smallest missing helper or runtime probe and add it as a bounded repo script")
    elif CATEGORY == "runtime_drift":
        suggestions.append("probe the active bundle by content markers instead of relying on filenames")
    else:
        suggestions.append("reduce the failure into a bounded observable probe before proposing a larger repair")
    return checks, suggestions


def main() -> int:
    parser = argparse.ArgumentParser(description="Bounded helper generated by the agent society toolsmith.")
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--observation", default="")
    args = parser.parse_args()

    repo_root = Path(args.repo_root)
    checks, suggestions = collect_checks(repo_root, args.observation)
    payload = {{
        "helper_name": HELPER_NAME,
        "purpose": PURPOSE,
        "category": CATEGORY,
        "status": "ready",
        "repo_root": str(repo_root),
        "checks": checks,
        "suggested_actions": suggestions,
    }}
    print(json.dumps(payload, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
"""


def create_helper_tool(repo_root: Path, helper_name: str, purpose: str, category: str | None = None) -> dict[str, object]:
    target_dir = repo_root / "scripts" / "openclaw" / "helpers"
    target_dir.mkdir(parents=True, exist_ok=True)

    inferred_category = infer_helper_category(helper_name, purpose, category)
    slug = normalize_slug(helper_name)
    target = target_dir / f"{slug}.py"
    target.write_text(render_helper(helper_name, purpose, inferred_category), encoding="utf-8")
    target.chmod(0o755)
    return {
        "helper_name": helper_name,
        "entrypoint": str(target.relative_to(repo_root)).replace("\\", "/"),
        "created": True,
        "category": inferred_category,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a bounded executable helper tool in the repo.")
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--helper-name", required=True)
    parser.add_argument("--purpose", required=True)
    parser.add_argument("--category")
    args = parser.parse_args()

    payload = create_helper_tool(
        repo_root=Path(args.repo_root),
        helper_name=args.helper_name,
        purpose=args.purpose,
        category=args.category,
    )
    print(json.dumps(payload, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
